[theme]
primaryColor = "#FFCC00"       # Heuvelman Geel
backgroundColor = "#FFFFFF"    # Wit
secondaryBackgroundColor = "#F0F2F6" # Heel lichtgrijs voor zijbalken
textColor = "#003366"          # Heuvelman Donkerblauw
font = "sans serif"

